### ISSUE TITLE
[feat, refactor] : 레지스터 토큰 추가 & 기본 정보 입력 API 구현

### ISSUE THREAD

**Issue by bbbang105** [KUSITMS-29th-TEAM-D/backend#12]
### 📝 Description

- 신규 유저라면, 액세스 토큰이 아닌 레지스터 토큰을 발급해 기본 정보를 입력 받도록 한다.

---

### 📝 Todo

- [x]  레지스터 토큰 추가
- [x] 기본 정보 입력 API 구현
- [x] 닉네임 중복 체크 API 구현
