### ISSUE TITLE
[refactor] : 정의하기 페르소나 리팩토링

### ISSUE THREAD

**Issue by bbbang105** [KUSITMS-29th-TEAM-D/backend#35]
### 📝 Description

- 조각 카드 앞 뒤 이미지 Enum 추가

---

### 📝 Todo

- [x] 조각 카드 앞 뒤 이미지 Enum 추가
- [x] DTO에 이미지 추가
- [x] 카카오톡 공유하기 시 사용할 GET 요청 추가
