### ISSUE TITLE
[refactor] : 엔터티 리팩토링 진행

### ISSUE THREAD

**Issue by bbbang105** [KUSITMS-29th-TEAM-D/backend#40]
### 📝 Description

- uuid 컬럼 제거
- Base Entity 적용
- 컬럼명 일부 수정
- 유저 

---

### 📝 Todo

- [x]  uuid 컬럼 제거
- [x] Base Entity 적용
- [x] 컬럼명 일부 수정
- [x] 유저 온보딩 정보 테이블 추가
