### ISSUE TITLE
[refactor] : 리팩토링 진행

### ISSUE THREAD

**Issue by bbbang105** [KUSITMS-29th-TEAM-D/backend#74]
### 📝 Description

- 전체적인 리팩토링을 진행한다.

---

### 📝 Todo
 
- [x] 이해하기 페르소나 질문 리팩토링
- [x] 이해하기 페르소나 에러 처리 추가
- [x] 이해하기 페르소나 답변 요약 반환 시 질문도 포함하도록 변경
- [x] 정의하기 페르소나 키워드 수정
- [x] 서비스 단 Transactional 리팩토링
- [ ] 소셜 로그인 성공 핸들러 리팩토링
- [ ] Security 보안 설정
